baseURL = "https://nav.bioitee.com"
languageCode = "zh-CN"
title = "Bio & IT 网址导航 | Hugo 主题"
theme = "WebStack-Hugo"
preserveTaxonomyNames = true
disablePathToLower = true
hasCJKLanguage = true
publishDir = "docs"


[params]
    author = "shenweiyan"
    description = "Webstack Hugo 网址导航 | Bio IT 爱好者"
    siteurl = "./"
    repository = "https://github.com/shenweiyan/WebStack-Hugo"
    enableLoad = true
    logosPath  = "assets/images/logos"

[params.qweather]
    key = "085791e805a24491b43b06cf58ab31e7"

[params.images]
    favicon           = "assets/images/favicon.png"
    backgroundImage   = "assets/images/bg.jpg"
    logoExpandLight   = "http://144.76.231.30:1313/assets/images/bioitee-expand-light.png"
    logoExpandDark    = "assets/images/bioitee-expand-dark.png"
    logoCollapseLight = "assets/images/logo-collapse-light.png"
    logoCollapseDark  = "assets/images/logo-collapse-dark.png"

[params.footer]
    copyright = '本站内容源自互联网，如有内容侵犯了你的权益，请联系删除相关内容，联系邮箱：ishenweiyan@foxmail.com <br/>&copy; 2021 - {year} By [WebStack-Hugo](https://github.com/shenweiyan/WebStack-Hugo) | [Bio IT 爱好者](https://www.bioitee.com/) | [粤ICP备16023717号](http://beian.miit.gov.cn/)<br/>'
